package com.smarttask.common.entity;

import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.time.LocalDateTime;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Base class for entities that need a generated identifier and audit timestamps.
 */
@Getter
@Setter
@SuperBuilder
@NoArgsConstructor
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    /**
     * Unique identifier generated by the persistence provider.
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Timestamp recorded when the entity is first persisted.
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp updated when the entity is modified.
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;
}
